### ISSUE TITLE
status?

### ISSUE THREAD

**Issue by eturk1** [njasm/KotWave#1]
Has the project been abandoned, or maybe permanently broken by changes at SoundCloud?

Many of us are dreaming of an Android Auto app for SoundCloud & API could help a Kotlin project.

**Comment by njasm** [comment]
Hello @eturk1 sorry to get back to you so late.

But yes, you are right, this project is on hold indefinitely due to Soundcloud constant changes without prior notice and lack of proper feedback regarding their public API to the eyes of FOSS projects that consume those services.

To be honest I don't feel that the public API of Soundcloud is not in their own judgment something that they are willing to support/invest.

**Comment by eturk1** [comment]
> But yes, you are right, this project is on hold indefinitely due to Soundcloud constant changes...
thanks for the update mate!
